/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.example.Apresentacao;

import org.example.Controle.CandidatoUtil;
import org.example.Controle.ImageUtil;
import org.example.Modelo.Candidato;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author alyss
 */
public class FrmCadastroCandidatos extends javax.swing.JDialog {

    /**
     * Creates new form frmCadastroCandidatos
     */

    public static String caminho_imagem = "";

    public FrmCadastroCandidatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preenche_lista();

    }

    CandidatoUtil c = new CandidatoUtil();
    FrmSelecionaArquivo a = new FrmSelecionaArquivo(null, rootPaneCheckingEnabled);
    ImageUtil iu = new ImageUtil();


    private void limpa_campos() {
        txt_nome.setText("");
        txt_cargo.setText("");
        txt_numero.setText("");
        pn_image.setText(".");
        pn_image.setIcon(null);
        caminho_imagem = "";

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        lis_candidados = new JList<>();
        txt_nome = new javax.swing.JTextField();
        lbl_nome = new JLabel();
        lbl_cargo = new JLabel();
        txt_cargo = new javax.swing.JTextField();
        lbl_numero = new JLabel();
        txt_numero = new javax.swing.JTextField();
        btn_movimentar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pn_image = new JLabel();
        btn_mudaFoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lis_candidados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lis_candidadosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lis_candidados);

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });
        txt_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nomeKeyTyped(evt);
            }
        });

        lbl_nome.setText("Nome:");

        lbl_cargo.setText("Cargo:");

        txt_cargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_cargoKeyTyped(evt);
            }
        });

        lbl_numero.setText("Número:");

        txt_numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_numeroKeyTyped(evt);
            }
        });

        btn_movimentar.setBackground(new java.awt.Color(102, 153, 0));
        btn_movimentar.setText("Cadastrar");
        btn_movimentar.setToolTipText("");
        btn_movimentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_movimentarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(191, 162));

        pn_image.setForeground(new java.awt.Color(255, 255, 255));
        pn_image.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pn_image, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pn_image, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addContainerGap())
        );

        btn_mudaFoto.setText("Selecionar foto");
        btn_mudaFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mudaFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbl_numero)
                                                        .addComponent(lbl_nome)
                                                        .addComponent(lbl_cargo))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txt_numero, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                                        .addComponent(txt_nome)
                                                        .addComponent(txt_cargo))
                                                .addGap(28, 28, 28)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(btn_mudaFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(btn_movimentar, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lbl_numero)
                                                        .addComponent(txt_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_nome))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lbl_cargo)
                                                        .addComponent(txt_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(btn_mudaFoto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_movimentar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(73, 73, 73))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_movimentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_movimentarActionPerformed
        //Verificações dos formulário
        boolean verifica = true;
        String erro = "";

        if (txt_numero.getText().trim().equals("0000")) {
            System.out.println("teste");
            verifica = false;
            erro = "Não pode criar um candidato com esse número, tente outro";
        }

        if ((txt_numero.getText().length() != 4) && verifica) {
            verifica = false;
            erro = "O número do candidato deve ter 4 caractéres";
        }

        if ((txt_nome.getText().length() < 5 || txt_nome.getText().length() > 15) && verifica) {
            verifica = false;
            erro = "O nome deve ter no mínimo 5 e no máximo 15 caractéres";
        }

        if ((txt_cargo.getText().length() < 5 || txt_cargo.getText().length() > 15) && verifica) {
            verifica = false;
            erro = "O cargo deve ter no mínimo 5 e no máximo 15 caractéres";
        }


        if (verifica) {
            try {
                Boolean result = c.adiciona_candidato(
                        FrmCadastroCandidatos.txt_nome.getText(),
                        FrmCadastroCandidatos.txt_cargo.getText(),
                        FrmCadastroCandidatos.txt_numero.getText(),
                        caminho_imagem
                );
                preenche_lista();

                if (result) {
                    JOptionPane.showMessageDialog(null, "Número de candidato já cadastrado");
                } else {
                    JOptionPane.showMessageDialog(null, "Candidato cadastrado!");
                    limpa_campos();
                }
            } catch (SQLException ex) {
                Logger.getLogger(FrmCadastroCandidatos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(FrmCadastroCandidatos.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, erro);
        }


    }//GEN-LAST:event_btn_movimentarActionPerformed

    private void btn_mudaFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mudaFotoActionPerformed
        a.setLocationRelativeTo(this);
        a.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_btn_mudaFotoActionPerformed

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void lis_candidadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lis_candidadosValueChanged
        System.out.println(evt);
    }//GEN-LAST:event_lis_candidadosValueChanged

    private void txt_numeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numeroKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) || txt_numero.getText().length() >= 4) {
            evt.consume();
        }

    }//GEN-LAST:event_txt_numeroKeyTyped

    private void txt_nomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomeKeyTyped
        if (txt_nome.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_nomeKeyTyped

    private void txt_cargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cargoKeyTyped
        if (txt_cargo.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_cargoKeyTyped


    //Preenche a lista com objetos
    private void preenche_lista() {
        DefaultListModel model = c.devolve_modelo_candidatos();
        lis_candidados.setModel(model);
        lis_candidados.setCellRenderer(new CreateListCellRenderer());


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmCadastroCandidatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(FrmCadastroCandidatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FrmCadastroCandidatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FrmCadastroCandidatos.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmCadastroCandidatos dialog = new FrmCadastroCandidatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public class CreateListCellRenderer extends DefaultListCellRenderer {
        public Component getListCellRendererComponent(
                JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            // I know DefaultListCellRenderer always returns a JLabel
            // super setups up all the defaults
            JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

            if (value instanceof Candidato) {
                Candidato course = (Candidato) value;

                label.setText(course.getNome() + " - " + course.getDs_numero());
            }


            return label;

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_movimentar;
    private javax.swing.JButton btn_mudaFoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private JLabel lbl_cargo;
    private JLabel lbl_nome;
    private JLabel lbl_numero;
    public static JList<String> lis_candidados;
    public static JLabel pn_image;
    public static javax.swing.JTextField txt_cargo;
    public static javax.swing.JTextField txt_nome;
    public static javax.swing.JTextField txt_numero;
    // End of variables declaration//GEN-END:variables
}
